#!/bin/bash

cd $(dirname $0)/..

echo --- apt-get
sudo apt-get -qq update
sudo apt-get install -y libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler
sudo apt-get install -y --no-install-recommends libboost-all-dev
sudo apt-get install -y libgflags-dev libgoogle-glog-dev liblmdb-dev libatlas-base-dev

echo --- npm install
npm install

echo --- npm test
npm test

