#!/bin/bash -e

# ( The android build system will pass us source, dest)
DEST=${2:-.}

# Heroku defines SOURCE_VERSION because the .git/ is not available, so use it if
# present and otherwise consult git
if [[ -z "$SOURCE_VERSION" ]]; then
  SOURCE_VERSION="$(git rev-parse HEAD)"
fi

# Official builds are untouched by germ-infested human hands
OFFICIAL=false
if [[ -n $DYNO ]]; then  # Heroku deployment?
  OFFICIAL=true
elif [[ -n $CI ]]; then  # CI environment?
  if [[ "$CI_PULL_REQUEST" = "false" ]]; then
    OFFICIAL=true
  fi
fi

mkdir -p $DEST/dist
rm -f $DEST/dist/index.json
DIST=$(node -p "\
  const gen = require('silk-core-version/gen');\
  JSON.stringify(gen({sha: '$SOURCE_VERSION', official: $OFFICIAL}))\
")
echo $DIST > $DEST/dist/index.json
cat $DEST/dist/index.json

if [[ "$DEST" != "." ]]; then
  cp -f package.json $DEST/package.json
  cp -f index.js $DEST/index.js
fi
