#!/bin/bash -e

# ( The android build system will pass us source, dest)
DEST=${2:-.}

# Heroku defines SOURCE_VERSION because the .git/ is not available, so use it if
# present and otherwise consult git
if [[ -z "$SOURCE_VERSION" ]]; then
  SOURCE_VERSION="$(git rev-parse HEAD)"
fi

# Official builds are untouched by germ-infested human hands
OFFICIAL=false
if [[ -n $DYNO ]]; then  # Heroku deployment?
  OFFICIAL=true
elif [[ -n $CI ]]; then  # CI environment?
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    OFFICIAL=true
  fi
fi

mkdir -p $DEST/dist
cat > $DEST/dist/index.json <<-EOF
	{
	  "branch": "$(source branch; echo $BRANCH)",
	  "bsp_api_id": "$(node -p "require('silk-bsp-version').bsp_api_id")",
	  "buildtime": "$(node -p "Date.now()")",
	  "fingerprint": "$BUILD_FINGERPRINT",
	  "official": $OFFICIAL,
	  "semver": "$(node -p "require('./package.json').version")",
	  "sha": "$SOURCE_VERSION"
	}
EOF
cat $DEST/dist/index.json

if [[ "$DEST" != "." ]]; then
  cp -f package.json $DEST/package.json
  cp -f index.js $DEST/index.js
fi
