#! /bin/bash -ex

if [[ -z $SILK_BOARD ]]; then
  echo "Must be run after : source build/envsetup.sh"
  exit 1
fi

if [[ -z $TRAVIS_BRANCH ]]; then
  echo "Please set TRAVIS_BRANCH"
  exit 1
fi

ensure_version() {
  pushd ../version
  npm install
  popd
}

get_version() {
  pushd ../version>/dev/null
  node -p "require('.').semver"
  popd>/dev/null
}

ensure_version

channel=${SILK_CHANNEL:-commit}
branch=$TRAVIS_BRANCH
os=$(uname | tr '[:upper:]' '[:lower:]')
version=$(get_version)
target_upload_path=$channel/$SILK_BOARD/$os/$branch/$version

# Produce target tarball
./archive dist
mkdir -p sos_release
tar -czf sos_release/target.tar.gz dist

# Build ccache tarball
pushd $HOME/.ccache/
mkdir -p $HOME/ccache_dist/
tar -czf $HOME/ccache_dist/ccache.tar.gz *
popd

if [[ -d ../../s3-artifacts ]]; then
  ../../s3-artifacts/bin/upload \
    silk-sos-release \
    $target_upload_path \
    $PWD/sos_release \
    --credentials sos_release

  ../../s3-artifacts/bin/upload \
    silk-sos-release \
    $CCACHE_PATH \
    $HOME/ccache_dist \
    --credentials sos_release
fi
