#!/bin/bash -e

source build/envsetup.sh force
make -j2

(
  set -x
  $PREBUILT_CCACHE -s
)

if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
  # We place this in script to ensure that when it fails it turns the build red.
  ./travis/artifacts
fi

exit 0
