#!/bin/bash -e

BOARD=$1
PRODUCT=$2

if [[ -z $BOARD ]]; then
  echo "Usage: $0 board [product]"
  exit 1
fi

set -x

./sync $BOARD $PRODUCT
source build/envsetup.sh
make -j4

# We place this in script to ensure that when it fails it turns the build red.
./travis/artifacts
