#! /bin/bash -ex

export PATH=./node_modules/.bin:$PATH

function npm_update {
  local ver=$(npm --version)
  local major=${ver:0:1}

  if [[ "$major" != "3" ]];
  then
    rm -rf node_modules
    npm install npm@3
  fi
  echo "Installing using npm $(npm --version)"
}


# Patches:
#
#  - webpack-allow-require-extensions.patch:
#
#    Allows babel-register to actually run.. This simply flags
#    require.extensions to be ignored.
#
#  - babel-allow-multiple-register-requires.patch:
#
#    Allows us to run babel-register multiple times (originally it relied on
#    module scope). This allows us to use the same babel-register N times while
#    reusing the preset cache... Ideally this should be upstreamed!
#
function patch_modules {
  patches=( patches/*.patch )
  for file in "${patches[@]}";
  do
    patch -N -p0 -i $file || echo
  done
}

npm_update
npm install
patch_modules
./node_modules/.bin/webpack

# Verify it actually works...
node -e 'require("../babel-register")'
