#!/bin/bash -e

current_pid=$$

if [[ -z $ANDROID_PRODUCT_OUT ]]; then
  echo "Please run |source build/envsetup.sh|"
  exit 1
fi

if [[ ! -d $ANDROID_PRODUCT_OUT ]]; then
  echo "Directory does not exist: $ANDROID_PRODUCT_OUT"
  exit 1
fi

# Without system-qemu.img changes to /system will not persist across emulator
# restarts
if [[ ! -f $ANDROID_PRODUCT_OUT/system-qemu.img ]]; then
  cp -v $ANDROID_PRODUCT_OUT/system{,-qemu}.img
fi

get_children() {
  pgrep -P $current_pid
}

# failsafe to ensure emulator closes cleanly.
cleanly_close_emulator() {
  echo "Interrupt! Killing emulator."
  # contains currently running emulator wrapper but not the underlying emulator
  for pid in $(get_children $current_pid); do
    # second level children this contains the real emulator.
    for child_pid in $(get_children $pid); do
      pids_to_kill+=("$child_pid")
    done
  done
  if [[ ! -z "${pids_to_kill[*]}" ]]; then
    ( set -x; kill "${pids_to_kill[*]}" )
  fi
}

trap cleanly_close_emulator HUP INT QUIT TERM
emulator -verbose -selinux permissive -show-kernel -no-skin -no-audio -no-window -memory 512 &
wait
exit 0
