#!/bin/bash -e

export BOARD=${1:?}
export PRODUCT=$2
VARIANT=${3:?}
if [[ $VARIANT = user ]]; then
  export NODE_ENV=production
fi

cd $(dirname $0)/..

source ci/before_script
../../ci-artifacts/logger timeout 90m ci/build
ERR=$?
if [[ $ERR -eq 0 ]]; then
  echo --- After success
  ci/after_success
  ERR=$?
fi

echo --- After build
if ${CI_DEBUG:-false}; then
  df -h
  du -h -d 1 * .repo
  du -h -d 2 out/target/product/
  du -h -d 1 ..
  du -hs .
fi

source ../../ci-artifacts/setup
../../ci-artifacts/upload || true

exit $ERR
